import '@/styles/globals.css';
import { checkTheme } from '@/lib/check-theme'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: checkTheme }} />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
